### ISSUE TITLE
npm ERR! 404 Not Found: @fengyuanchen/loader

### ISSUE THREAD

**Issue by callmewhy** [fengyuanchen/loader#1]
npm install failed while using `npm install @fengyuanchen/loader`.

But it works with `npm install fengyuanchen/loader`, which will pull the repo from github.

**Comment by fengyuanchen** [comment]
I guess you still use the old NPM v1.x. Please download and install the latest [Node.js](https://nodejs.org/en/) (with the latest NPM built-in).

**Comment by callmewhy** [comment]
npm -v
3.3.6

**Comment by fengyuanchen** [comment]
https://www.npmjs.com/package/@fengyuanchen/loader

**Comment by callmewhy** [comment]
It seems that the registry of taobao hasn't update their repo. 

It's fixed while setting registry to https://registry.npmjs.org/
